import Link from "next/link";
import {requireAdmin} from "@/lib/auth";
import {NaturalImporter} from "@/components/natural-importer";
import {NaturalStatusActions} from "@/components/natural-status-actions";
import {typeLabel} from "@/lib/naturalWisdom";

export default async function NatureAdmin({searchParams}:{searchParams:Promise<{error?:string;type?:string;level?:string;imported?:string;updated?:string}>}){
 const {db}=await requireAdmin();const p=await searchParams;let q=db.from("natural_wisdom_entries").select("id,slug,entry_number,entry_type,name_zh,ymos_level,status,manually_edited").order("created_at",{ascending:false});if(p.type)q=q.eq("entry_type",p.type);if(p.level)q=q.eq("ymos_level",p.level);const {data}=await q;
 return <div className="mx-auto max-w-7xl px-5 py-10"><p className="eyebrow">NATURAL INTELLIGENCE ADMIN</p><h1 className="mt-2 text-4xl">自然智慧條目</h1>{p.error&&<p className="sans mt-5 whitespace-pre-wrap border border-red-700/30 p-4 text-red-900">{p.error}</p>}{p.imported&&<p className="sans mt-5 bg-[#dce0d4] p-4">已匯入為待審核。</p>}{p.updated&&<p className="sans mt-5 bg-[#dce0d4] p-4">狀態已更新。</p>}<div className="mt-8 grid gap-8 lg:grid-cols-[1fr_1.2fr]"><NaturalImporter/><section><form className="sans flex gap-3 text-sm"><select name="type" defaultValue={p.type??""} className="field !mt-0"><option value="">全部類型</option><option value="animal">動物</option><option value="plant">植物</option><option value="herb">中藥</option></select><select name="level" defaultValue={p.level??""} className="field !mt-0"><option value="">全部層級</option><option value="individual">個體</option><option value="team">團隊</option><option value="system">系統</option><option value="ecosystem">生態</option></select><button className="border px-4">篩選</button></form><div className="card mt-4 overflow-x-auto"><table className="work-table"><thead><tr><th>條目</th><th>層級</th><th>狀態</th><th>操作</th></tr></thead><tbody>{data?.map(x=><tr key={x.id}><td>#{x.entry_number} {typeLabel(x.entry_type)} · <Link href={`/nature/${x.slug}`}>{x.name_zh}</Link></td><td>{x.ymos_level}</td><td>{x.status}</td><td><NaturalStatusActions id={x.id}/></td></tr>)}</tbody></table>{!data?.length&&<p className="sans p-10 text-center">尚無條目</p>}</div></section></div></div>
}
