"use client";
import { useMemo, useState } from "react";
import { strategyCaseSchema } from "@/types/strategyCase";
import { StrategyCaseDetail } from "@/components/strategy-case-detail";

type Result={error?:string;issues?:Array<{path:string;message:string}>;warnings?:Array<{kind:string;name:string;caseDate?:string}>;previewUrl?:string};
export function ImportCaseClient(){
 const [mode,setMode]=useState<"json"|"text">("json"),[raw,setRaw]=useState(""),[secret,setSecret]=useState(""),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false);
 const validation=useMemo(()=>{if(!raw.trim())return null;try{return strategyCaseSchema.safeParse(JSON.parse(raw));}catch{return {success:false as const,error:{issues:[{path:[],message:"JSON 語法錯誤"}]}};}},[raw]);
 const parsed=validation?.success?validation.data:null;
 async function submit(force=false){if(!parsed)return;setBusy(true);setResult(null);try{const response=await fetch("/api/import/strategy-case",{method:"POST",headers:{"content-type":"application/json","x-import-secret":secret},body:JSON.stringify({data:parsed,force})});const body=await response.json() as Result;setResult(body);if(response.ok&&body.previewUrl)location.href=body.previewUrl;}finally{setBusy(false);}}
 return <div className="max-w-6xl mx-auto px-5 py-16"><p className="eyebrow">PRIVATE IMPORT</p><h1 className="text-4xl mt-3">完整每日案例匯入</h1><p className="sans text-sm text-[#6d706b] mt-4">企業、領導者、IP、兵法與 YMOS 是同一篇研究的五個鏡頭。</p><div className="flex gap-2 mt-8"><button onClick={()=>setMode("json")} className={`sans px-4 py-2 border ${mode==="json"?"bg-[#34423a] text-white":""}`}>模式 A・完整 JSON</button><button onClick={()=>setMode("text")} className={`sans px-4 py-2 border ${mode==="text"?"bg-[#34423a] text-white":""}`}>模式 B・純文字</button></div>{mode==="text"?<div className="mt-8 p-8 border border-[#34423a]/20"><h2 className="text-2xl">純文字解析・第二階段</h2><p className="sans text-[#6d706b] mt-3">介面已預留；目前請使用 JSON 模式，後續會加入逐欄解析與修改表單。</p><textarea disabled rows={12} className="w-full mt-6 p-4 bg-white/40 border" placeholder="貼上完整純文字文章"/></div>:<div className="mt-8 grid lg:grid-cols-[1fr_320px] gap-6"><div><label className="sans text-sm">完整 StrategyCase JSON<textarea value={raw} onChange={e=>setRaw(e.target.value)} rows={28} spellCheck={false} className="block w-full mt-2 p-4 bg-white/60 border border-[#34423a]/20 font-mono text-xs"/></label></div><aside className="space-y-5"><label className="sans text-sm">IMPORT_SECRET<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} className="block w-full mt-2 p-3 bg-white/60 border"/></label><div className="p-4 border border-[#34423a]/20 sans text-sm">{!validation?<p>貼上 JSON 後即時檢查。</p>:validation.success?<p className="text-green-800">格式與欄位驗證通過。</p>:<ul className="text-red-800 space-y-2">{validation.error.issues.map((issue,index)=><li key={index}><b>{issue.path.join(".")||"JSON"}</b>：{issue.message}</li>)}</ul>}</div><button disabled={!parsed||!secret||busy} onClick={()=>submit(false)} className="w-full sans px-5 py-3 bg-[#34423a] text-white disabled:opacity-40">{busy?"匯入中…":"確認後匯入"}</button>{result?.error&&<div className="p-4 border border-red-800/30 sans text-sm"><p>{result.error}</p>{result.issues?.map(x=><p key={x.path}>{x.path}：{x.message}</p>)}{result.warnings?.length&&<><ul className="mt-3">{result.warnings.map((x,i)=><li key={i}>{x.kind}：{x.name} {x.caseDate}</li>)}</ul><button onClick={()=>submit(true)} className="mt-4 underline">確認風險並強制建立新案例</button></>}</div>}</aside></div>}{parsed&&<div className="mt-16 border-t-2 border-[#b59962]"><p className="eyebrow mt-8">LIVE PREVIEW</p><StrategyCaseDetail item={parsed} preview/></div>}</div>;
}
