import {z} from "zod";
export const naturalEntryTypes=["animal","plant","herb","fungus","microorganism"] as const;
export const ymosLevels=["individual","team","system","ecosystem"] as const;
export const naturalStatuses=["draft","pending_review","published","rejected"] as const;
const optional=z.string().trim().nullable().optional();const required=z.string().trim().min(1,"不可空白");const jsonStrings=z.array(required).default([]);
export const naturalWisdomSchema=z.object({id:z.string().uuid().optional(),entryNumber:z.number().int().positive(),entryType:z.enum(naturalEntryTypes),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),parentEntryId:z.string().uuid().nullable().optional(),nameZh:required,nameEn:optional,scientificName:optional,subtitle:required,summary:required,ymosLevel:z.enum(ymosLevels),primaryElement:optional,secondaryElement:optional,lifeRole:optional,coreAbility:required,keywords:jsonStrings,biologyProfile:z.record(z.unknown()).default({}),evolutionBackground:required,survivalStrategy:required,behaviorStrategy:optional,groupCooperation:optional,decisionModel:optional,riskManagement:required,environmentAdaptation:required,ecologicalInteractions:optional,herbalName:optional,medicinalPart:optional,natureFlavor:optional,meridianEntry:optional,traditionalFunctions:optional,pairingLogic:optional,processingMethods:optional,classicalHistory:optional,modernResearch:optional,risksAndContraindications:optional,evidenceLimits:optional,ymosPrinciples:jsonStrings,yuLifeSystemInsight:optional,yuTcmMapping:optional,educationInsight:optional,managementInsight:optional,brandInsight:optional,businessInsight:optional,aiInsight:optional,todayInspiration:required,wisdomSentence:required,coverImageUrl:z.string().url().nullable().optional(),sources:z.array(z.object({title:required,url:z.string().url().optional(),sourceType:z.string().optional()})).default([]),status:z.enum(naturalStatuses).default("pending_review"),manuallyEdited:z.boolean().default(false),publishedAt:z.string().nullable().optional(),createdAt:z.string().optional(),updatedAt:z.string().optional()});
export type NaturalWisdomEntry=z.infer<typeof naturalWisdomSchema>;
export const naturalIssueSchema=z.object({id:z.string().uuid().optional(),issueNumber:z.number().int().positive(),publishedDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),dailyTheme:required,animalEntryId:z.string().uuid(),plantEntryId:z.string().uuid(),crossInsight:required,dailyLifeWisdom:required,status:z.enum(naturalStatuses).default("pending_review")});
export const levelLabels={individual:{zh:"個體能力",en:"Individual",definition:"單一生命體感知、決策與適應的能力"},team:{zh:"團隊能力",en:"Team",definition:"群體協作、分工與共同防衛的能力"},system:{zh:"系統能力",en:"System",definition:"維持循環、回饋與韌性的能力"},ecosystem:{zh:"生態能力",en:"Ecosystem",definition:"跨物種互動、共生與長期演化的能力"}} as const;
