import { ExternalLink } from "lucide-react";
import type { StrategyCase } from "@/types/strategyCase";

const Section=({number,title,children}:{number:string;title:string;children:React.ReactNode})=><section className="py-12 border-t border-[#34423a]/15"><div className="grid md:grid-cols-[150px_1fr] gap-6"><div><span className="eyebrow">{number}</span><h2 className="text-2xl mt-2">{title}</h2></div><div>{children}</div></div></section>;
const Grid=({items}:{items:Array<[string,string|string[]]>})=><dl className="grid sm:grid-cols-2 gap-x-10 gap-y-6">{items.map(([key,value])=><div key={key}><dt className="sans text-xs tracking-wider text-[#72806b] mb-2">{key}</dt><dd className="leading-7">{Array.isArray(value)?value.join(" → "):value}</dd></div>)}</dl>;

export function StrategyCaseDetail({item,preview=false}:{item:StrategyCase;preview?:boolean}){return <article>
  <header className="max-w-5xl mx-auto px-5 pt-14 sm:pt-24 pb-16">{preview&&<p className="sans inline-block px-3 py-1 bg-[#c6b180]/30 mb-5">預覽・{item.status}</p>}<p className="eyebrow">{item.caseDate.replaceAll("-"," · ")} · COMPLETE CASE</p><h1 className="text-4xl sm:text-6xl leading-[1.35] mt-5">{item.title}</h1><p className="text-2xl text-[#72806b] mt-4">{item.subtitle}</p><p className="sans text-lg leading-8 text-[#6d706b] mt-8 max-w-3xl">{item.summary}</p><p className="sans mt-6 p-5 border-l-2 border-[#b59962]">{item.centralTheme}</p><div className="flex flex-wrap gap-2 mt-8">{item.tags.map(tag=><span key={tag} className="sans text-xs px-3 py-1 bg-[#dce0d4]">{tag}</span>)}</div></header>
  <div className="bg-[#34423a] text-[#f5f1e8]"><div className="max-w-5xl mx-auto px-5 py-12 grid sm:grid-cols-3 gap-8 text-center">{[["企業",item.company.name],["領導者",item.leader.name],["IP",item.ip.name]].map(([key,value])=><div key={key}><p className="eyebrow !text-[#c6b180]">{key}</p><p className="text-xl mt-2">{value}</p></div>)}</div></div>
  <div className="max-w-5xl mx-auto px-5">
   <Section number="壹" title="企業案例"><Grid items={[["企業／產業",`${item.company.name}${item.company.englishName?`・${item.company.englishName}`:""}・${item.company.industry}`],["創辦背景",item.company.foundingBackground],["時間軸",item.company.timeline],["第一波紅利",item.company.firstWaveDividend],["創業核心",item.company.foundingCore],["商業飛輪",item.company.businessFlywheel],["收入來源",item.company.revenueSources],["最脆弱收入",item.company.vulnerableRevenue],["組織成熟度",item.company.organizationalMaturity],["單點失效",item.company.singlePointOfFailure],["危機路徑",item.company.crisisPath],["組織類型",item.company.organizationType]]}/></Section>
   <Section number="貳" title="政權／領導者案例"><Grid items={[["人物／政權",`${item.leader.name}・${item.leader.regime}`],["時代",item.leader.era],["歷史背景",item.leader.historicalBackground],["核心困局",item.leader.coreDilemma],["破局方法",item.leader.breakthroughMethod],["制度設計",item.leader.institutionalDesign],["用人策略",item.leader.talentStrategy],["戰略取捨",item.leader.strategicTradeoff],["歷史代價",item.leader.historicalCost],["參考文獻",item.leader.references]]}/></Section>
   <Section number="參" title="IP 案例"><Grid items={[["名稱／類型",`${item.ip.name}${item.ip.englishName?`・${item.ip.englishName}`:""}・${item.ip.type}`],["起源",item.ip.origin],["核心敘事",item.ip.coreNarrative],["角色設定",item.ip.characterDesign],["情緒鉤子",item.ip.emotionalHook],["世界觀",item.ip.worldBuilding],["符號系統",item.ip.symbolSystem],["社群機制",item.ip.communityMechanism],["平台紅利",item.ip.platformDividend],["商業變現",item.ip.monetization],["長紅機制",item.ip.longevityMechanism],["風險反噬",item.ip.backlashRisk]]}/></Section>
   <Section number="肆" title="兵法對照"><blockquote className="text-3xl leading-relaxed text-[#72806b]">「{item.strategy.quotation}」</blockquote><p className="eyebrow mt-3">{item.strategy.source}</p><p className="sans mt-6 leading-8">{item.strategy.interpretation}</p><h3 className="eyebrow mt-8">三鏡頭共同邏輯</h3><p className="sans mt-3 leading-8">{item.strategy.sharedLogic}</p></Section>
   <Section number="伍" title="YMOS 完整六層"><div className="space-y-4">{[["觀耳辨證",item.ymos.observationEntry],["余氏生命系統學",item.ymos.coreMethod],["耳林高手",item.ymos.educationProduct],["醫生醫世小方茶",item.ymos.lifestyleProduct],["YMOS",item.ymos.operatingSystem],["理解生命、理解系統、理解世界運行",item.ymos.brandSpirit]].map(([name,insight],index)=><div key={name} className="card p-5 flex gap-5"><span className="text-[#b59962]">{String(index+1).padStart(2,"0")}</span><div><h3>{name}</h3><p className="sans text-sm text-[#6d706b] mt-2">{insight}</p></div></div>)}</div></Section>
   <Section number="陸" title="策略輸出"><h3 className="text-xl">策略結論</h3><p className="sans leading-8 mt-3">{item.actions.strategicConclusion}</p><h3 className="eyebrow mt-10 mb-4">行動建議</h3><ol className="space-y-4">{item.actions.actionItems.map((action,index)=><li key={action} className="flex gap-4"><b className="text-[#b59962] font-normal">{String(index+1).padStart(2,"0")}</b><span>{action}</span></li>)}</ol><h3 className="eyebrow mt-10 mb-4">風險提醒</h3><ul className="sans list-disc pl-5 space-y-2 text-[#6d706b]">{item.actions.riskWarnings.map(x=><li key={x}>{x}</li>)}</ul><h3 className="eyebrow mt-10 mb-4">余老師判讀</h3><p className="sans leading-8">{item.actions.teacherInsight}</p></Section>
   <Section number="源" title="資料來源"><ul className="space-y-5 sans text-sm">{item.sources.map(source=><li key={source.url}><a className="inline-flex gap-2 items-center hover:text-[#72806b]" href={source.url} target="_blank" rel="noreferrer">{source.title}<ExternalLink size={13}/></a><p className="text-[#6d706b] mt-1">{source.sourceType}・{source.note}</p></li>)}</ul></Section>
  </div>
 </article>}
