import type { Thought } from "@/types/thought";
import { labels, maturityLevels, primaryElements, secondaryElements, thoughtStatuses, thoughtTypes } from "@/types/thought";
import { saveThought } from "@/app/thought-actions";
type CaseOption={id:string;title:string};
export function ThoughtForm({item,cases,error}:{item?:Thought;cases:CaseOption[];error?:string}){const input="field";return <form action={saveThought} className="mt-8 space-y-8">{item?.id&&<input type="hidden" name="id" value={item.id}/>} {error&&<p className="sans whitespace-pre-wrap border border-red-700/30 p-4 text-red-900">{error}</p>}
 <fieldset className="card p-6"><legend className="px-2 text-xl">基本內容</legend><div className="grid gap-5 sm:grid-cols-2"><label className="sans text-sm">日期<input required type="date" name="thought_date" defaultValue={item?.thought_date??new Date().toISOString().slice(0,10)} className={input}/></label><label className="sans text-sm">思想類型<select name="thought_type" defaultValue={item?.thought_type??"note"} className={input}>{thoughtTypes.map(x=><option key={x} value={x}>{labels.thoughtType[x]}</option>)}</select></label></div><label className="sans mt-5 block text-sm">標題<input required name="title" defaultValue={item?.title} className={input}/></label><label className="sans mt-5 block text-sm">摘要<textarea name="summary" rows={3} defaultValue={item?.summary??""} className={input}/></label><label className="sans mt-5 block text-sm">完整內容<textarea required name="content" rows={12} defaultValue={item?.content} className={input}/></label><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="sans text-sm">分類<input name="category" defaultValue={item?.category??""} className={input}/></label><label className="sans text-sm">標籤<input name="tags" defaultValue={item?.tags?.join("、")} className={input} placeholder="五行、管理、AI"/></label></div></fieldset>
 <fieldset className="card p-6"><legend className="px-2 text-xl">五行定位</legend><div className="grid gap-5 sm:grid-cols-2"><label className="sans text-sm">主五行<select name="primary_element" defaultValue={item?.primary_element??"未分類"} className={input}>{primaryElements.map(x=><option key={x}>{x}</option>)}</select></label><label className="sans text-sm">次五行<select name="secondary_element" defaultValue={item?.secondary_element??"無"} className={input}>{secondaryElements.map(x=><option key={x}>{x}</option>)}</select></label></div></fieldset>
 <fieldset className="card p-6"><legend className="px-2 text-xl">資料來源</legend><div className="grid gap-5 sm:grid-cols-2"><label className="sans text-sm">來源類型<input name="source_type" defaultValue={item?.source_type??""} className={input}/></label><label className="sans text-sm">關聯策略案例<select name="source_article_id" defaultValue={item?.source_article_id??""} className={input}><option value="">不關聯</option>{cases.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label></div><label className="sans mt-5 block text-sm">來源說明<input name="source_reference" defaultValue={item?.source_reference??""} className={input}/></label></fieldset>
 <fieldset className="card p-6"><legend className="px-2 text-xl">整理狀態</legend><div className="grid gap-5 sm:grid-cols-2"><label className="sans text-sm">狀態<select name="status" defaultValue={item?.status??"inbox"} className={input}>{thoughtStatuses.map(x=><option value={x} key={x}>{labels.status[x]}</option>)}</select></label><label className="sans text-sm">成熟程度<select name="maturity_level" defaultValue={item?.maturity_level??"idea"} className={input}>{maturityLevels.map(x=><option value={x} key={x}>{labels.maturity[x]}</option>)}</select></label></div><div className="sans mt-5 flex gap-6 text-sm"><label><input type="checkbox" name="is_favorite" defaultChecked={item?.is_favorite}/> 收藏</label><label><input type="checkbox" name="manually_edited" defaultChecked={item?.manually_edited}/> 人工編輯</label></div></fieldset>
 <button className="sans bg-[#34423a] px-6 py-3 text-white">儲存每日思想</button></form>}
