import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { articles } from "@/data/articles";
import { getPublishedArticle } from "@/lib/articles-repository";

export function generateStaticParams(){return articles.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const a=await getPublishedArticle((await params).slug);return {title:a?.title ?? "找不到文章",description:a?.excerpt}}
const Section=({number,title,children}:{number:string,title:string,children:React.ReactNode})=><section className="py-12 border-t border-[#34423a]/15"><div className="grid md:grid-cols-[150px_1fr] gap-6"><div><span className="eyebrow">{number}</span><h2 className="text-2xl mt-2">{title}</h2></div><div>{children}</div></div></section>;
const Grid=({items}:{items:Array<[string,string|string[]]>})=><dl className="grid sm:grid-cols-2 gap-x-10 gap-y-6">{items.map(([k,v])=><div key={k}><dt className="sans text-xs tracking-wider text-[#72806b] mb-2">{k}</dt><dd className="leading-7">{Array.isArray(v)?v.join(" → "):v}</dd></div>)}</dl>;

export default async function ArticleDetail({params}:{params:Promise<{slug:string}>}){const a=await getPublishedArticle((await params).slug);if(!a)notFound();return <article>
  <header className="max-w-5xl mx-auto px-5 pt-14 sm:pt-24 pb-16"><Link href="/articles" className="sans text-xs inline-flex gap-2 items-center text-[#6d706b]"><ArrowLeft size={14}/> 返回每日研究</Link><p className="eyebrow mt-14">{a.publishedAt.replaceAll("-"," · ")} · DAILY CASE</p><h1 className="text-4xl sm:text-6xl leading-[1.35] mt-5">{a.title}</h1><p className="sans text-lg leading-8 text-[#6d706b] mt-8 max-w-3xl">{a.excerpt}</p><div className="flex flex-wrap gap-2 mt-8">{a.tags.map(t=><span key={t} className="sans text-xs px-3 py-1 bg-[#dce0d4]">{t}</span>)}</div></header>
  <div className="bg-[#34423a] text-[#f5f1e8]"><div className="max-w-5xl mx-auto px-5 py-12 grid sm:grid-cols-3 gap-8 text-center">{[["企業",a.company.name],["領導者",a.leader.name],["IP",a.ip.name]].map(([k,v])=><div key={k}><p className="eyebrow !text-[#c6b180]">{k}</p><p className="text-xl mt-2">{v}</p></div>)}</div></div>
  <div className="max-w-5xl mx-auto px-5">
    <Section number="壹" title="企業案例"><Grid items={[["企業／產業",`${a.company.name}・${a.company.industry}`],["創辦背景",a.company.foundingBackground],["時間軸",a.company.timeline],["第一波紅利",a.company.firstDividend],["創業核心",a.company.core],["商業飛輪",a.company.flywheel],["收入來源",a.company.revenue],["最脆弱收入",a.company.fragileRevenue],["組織化程度",a.company.organizationLevel],["單點失效",a.company.singlePointFailure],["信任危機路徑",a.company.trustCrisisPath],["組織類型",a.company.organizationType]]}/></Section>
    <Section number="貳" title="領導者案例"><Grid items={[["人物／政權",`${a.leader.name}・${a.leader.regime}`],["時代背景",a.leader.era],["核心困局",a.leader.dilemma],["破局方法",a.leader.breakthrough],["制度設計",a.leader.institution],["用人策略",a.leader.talentStrategy],["戰略取捨",a.leader.tradeoff],["歷史代價",a.leader.historicalCost],["文獻來源",a.leader.sources]]}/></Section>
    <Section number="參" title="IP 案例"><Grid items={[["名稱／類型",`${a.ip.name}・${a.ip.type}`],["起源",a.ip.origin],["核心敘事",a.ip.narrative],["角色設定",a.ip.characters],["情緒鉤子",a.ip.emotionalHook],["世界觀",a.ip.worldview],["符號系統",a.ip.symbols],["社群機制",a.ip.community],["平台紅利",a.ip.platformDividend],["商業變現",a.ip.monetization],["長紅機制",a.ip.longevity],["風險反噬",a.ip.backlashRisk]]}/></Section>
    <Section number="肆" title="兵法對照"><blockquote className="text-3xl leading-relaxed text-[#72806b]">「{a.stratagem.title}」</blockquote><p className="eyebrow mt-3">{a.stratagem.source}</p><p className="sans mt-6 leading-8">{a.stratagem.interpretation}</p></Section>
    <Section number="伍" title="YMOS 六層"><div className="space-y-4">{a.ymosLayers.map((x,i)=><div key={x.layer} className="card p-5 flex gap-5"><span className="text-[#b59962]">0{i+1}</span><div><h3>{x.layer}</h3><p className="sans text-sm text-[#6d706b] mt-2">{x.insight}</p></div></div>)}</div></Section>
    <Section number="陸" title="策略行動"><ol className="space-y-4">{a.actions.map((x,i)=><li key={x} className="flex gap-4"><b className="text-[#b59962] font-normal">{String(i+1).padStart(2,"0")}</b><span>{x}</span></li>)}</ol><h3 className="eyebrow mt-10 mb-4">風險提醒</h3><ul className="sans list-disc pl-5 space-y-2 text-[#6d706b]">{a.risks.map(x=><li key={x}>{x}</li>)}</ul></Section>
    <Section number="源" title="資料來源"><ul className="space-y-3 sans text-sm">{a.sources.map(x=><li key={x.url}><a className="inline-flex gap-2 items-center hover:text-[#72806b]" href={x.url} target="_blank" rel="noreferrer">{x.label}<ExternalLink size={13}/></a></li>)}</ul></Section>
  </div></article>}
