-- Additive, isolated YMOS Natural Intelligence schema.
create table if not exists public.natural_wisdom_entries(
 id uuid primary key default gen_random_uuid(),entry_number integer not null check(entry_number>0),entry_type text not null check(entry_type in('animal','plant','herb','fungus','microorganism')),slug text not null unique,parent_entry_id uuid references public.natural_wisdom_entries(id) on delete set null,
 name_zh text not null,name_en text,scientific_name text,subtitle text not null,summary text not null,ymos_level text not null check(ymos_level in('individual','team','system','ecosystem')),primary_element text,secondary_element text,life_role text,core_ability text not null,keywords jsonb not null default '[]',biology_profile jsonb not null default '{}',
 evolution_background text not null,survival_strategy text not null,behavior_strategy text,group_cooperation text,decision_model text,risk_management text not null,environment_adaptation text not null,ecological_interactions text,
 herbal_name text,medicinal_part text,nature_flavor text,meridian_entry text,traditional_functions text,pairing_logic text,processing_methods text,classical_history text,modern_research text,risks_and_contraindications text,evidence_limits text,
 ymos_principles jsonb not null default '[]',yu_life_system_insight text,yu_tcm_mapping text,education_insight text,management_insight text,brand_insight text,business_insight text,ai_insight text,today_inspiration text not null,wisdom_sentence text not null,cover_image_url text,sources jsonb not null default '[]',
 status text not null default 'pending_review' check(status in('draft','pending_review','published','rejected')),manually_edited boolean not null default false,published_at timestamptz,created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(entry_type,entry_number)
);
create table if not exists public.natural_daily_issues(id uuid primary key default gen_random_uuid(),issue_number integer not null unique,published_date date not null unique,daily_theme text not null,animal_entry_id uuid not null references public.natural_wisdom_entries(id),plant_entry_id uuid not null references public.natural_wisdom_entries(id),cross_insight text not null,daily_life_wisdom text not null,status text not null default 'pending_review' check(status in('draft','pending_review','published','rejected')),created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists natural_entry_type_idx on public.natural_wisdom_entries(entry_type,status);create index if not exists natural_ymos_level_idx on public.natural_wisdom_entries(ymos_level,status);create index if not exists natural_status_idx on public.natural_wisdom_entries(status);create index if not exists natural_published_at_idx on public.natural_wisdom_entries(published_at desc);create index if not exists natural_daily_date_idx on public.natural_daily_issues(published_date desc,status);
create trigger touch_natural_entries before update on public.natural_wisdom_entries for each row execute function public.touch_updated_at();create trigger touch_natural_issues before update on public.natural_daily_issues for each row execute function public.touch_updated_at();
alter table public.natural_wisdom_entries enable row level security;alter table public.natural_daily_issues enable row level security;
create policy "public reads published natural entries" on public.natural_wisdom_entries for select using(status='published' or created_by=auth.uid());create policy "owners manage natural entries" on public.natural_wisdom_entries for all to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());create policy "public reads published natural issues" on public.natural_daily_issues for select using(status='published' or created_by=auth.uid());create policy "owners manage natural issues" on public.natural_daily_issues for all to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
