-- Additive, non-destructive Human Body Atlas schema.
create table if not exists public.body_articles(
 id uuid primary key default gen_random_uuid(),slug text not null unique,day_number integer not null unique check(day_number>0),publish_date date not null unique,
 title text not null,subtitle text,organ_name_zh text not null,organ_name_en text not null,summary text not null,core_positioning text not null,
 primary_system text not null,related_systems text[] not null default '{}',primary_element text not null check(primary_element in('木','火','土','金','水')),
 related_elements text[] not null default '{}',element_reasoning text,axes text[] not null default '{}',tags text[] not null default '{}',content jsonb not null,
 status text not null default 'pending_review' check(status in('draft','pending_review','published')),manually_edited boolean not null default false,
 created_by uuid not null default auth.uid() references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint body_content_object check(jsonb_typeof(content)='object')
);
create table if not exists public.physiological_axes(
 id uuid primary key default gen_random_uuid(),slug text not null unique,name_zh text not null unique,name_en text not null,organs text[] not null default '{}',systems text[] not null default '{}',
 communication_routes text[] not null default '{}',core_functions text[] not null default '{}',related_elements text[] not null default '{}',yu_interpretation text not null,
 evidence_level text not null check(evidence_level in('established','widely_researched','emerging','yu_hypothesis')),related_article_ids uuid[] not null default '{}',created_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.body_organs(
 id uuid primary key default gen_random_uuid(),canonical_name_zh text not null unique,canonical_name_en text not null unique,aliases text[] not null default '{}',system text not null,
 status text not null default 'planned' check(status in('planned','collected')),published_article_id uuid references public.body_articles(id) on delete set null,published_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists body_articles_date_idx on public.body_articles(publish_date desc);create index if not exists body_articles_system_idx on public.body_articles(primary_system,status);create index if not exists body_articles_element_idx on public.body_articles(primary_element,status);create index if not exists body_articles_axes_idx on public.body_articles using gin(axes);create index if not exists body_articles_tags_idx on public.body_articles using gin(tags);create index if not exists body_organs_aliases_idx on public.body_organs using gin(aliases);create index if not exists axes_organs_idx on public.physiological_axes using gin(organs);
create trigger touch_body_articles before update on public.body_articles for each row execute function public.touch_updated_at();create trigger touch_physiological_axes before update on public.physiological_axes for each row execute function public.touch_updated_at();create trigger touch_body_organs before update on public.body_organs for each row execute function public.touch_updated_at();
alter table public.body_articles enable row level security;alter table public.physiological_axes enable row level security;alter table public.body_organs enable row level security;
create policy "public reads published body articles" on public.body_articles for select using(status='published' or created_by=auth.uid());create policy "admins manage body articles" on public.body_articles for all to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
create policy "authenticated reads axes" on public.physiological_axes for select to authenticated using(true);create policy "admins manage axes" on public.physiological_axes for all to authenticated using(exists(select 1 from public.profiles where id=auth.uid())) with check(exists(select 1 from public.profiles where id=auth.uid()));
create policy "authenticated reads organ index" on public.body_organs for select to authenticated using(true);create policy "admins manage organ index" on public.body_organs for all to authenticated using(exists(select 1 from public.profiles where id=auth.uid())) with check(exists(select 1 from public.profiles where id=auth.uid()));
insert into public.body_organs(canonical_name_zh,canonical_name_en,aliases,system,status) values
('大腦','Brain',array['腦'],'神經系統','collected'),('心臟','Heart',array['心'],'心血管系統','collected'),('肺','Lungs',array['肺臟'],'呼吸系統','collected'),('肝臟','Liver',array['肝'],'肝膽系統','collected'),('胰臟','Pancreas',array['胰腺'],'內分泌系統','collected'),('腎臟','Kidneys',array['腎'],'泌尿系統','collected'),('胃','Stomach',array[]::text[],'消化系統','collected'),('小腸','Small Intestine',array[]::text[],'消化系統','collected'),('大腸','Large Intestine',array['結腸'],'消化系統','collected'),('膽囊','Gallbladder',array['膽'],'肝膽系統','collected'),('脾臟','Spleen',array['西醫脾臟','中醫脾功能系統'],'免疫與淋巴系統','collected'),('食道','Esophagus',array['食管'],'消化系統','collected'),('膀胱','Urinary Bladder',array[]::text[],'泌尿系統','collected'),('甲狀腺','Thyroid Gland',array[]::text[],'內分泌系統','collected'),('胸腺','Thymus',array[]::text[],'免疫與淋巴系統','collected'),('腦下垂體','Pituitary Gland',array['垂體'],'內分泌系統','collected'),('下視丘','Hypothalamus',array['下丘腦'],'神經系統','collected') on conflict(canonical_name_zh) do nothing;
